<?php

namespace App\Helpers;

class Inspiring {
    public static function quote() {
        return collect([
            'Quando vires um homem bom, tenta imitá-lo; quando vires um homem mau, examina-te a ti mesmo. - Confúcio',
            'Para ver muita coisa é preciso despregar os olhos de si mesmo. - Friedrich Nietzsche',
            'Sua tarefa é descobrir o seu trabalho e, então, com todo o coração, dedicar-se a ele. - Buda',
            'Somos o que pensamos. Tudo o que somos surge com nossos pensamentos. Com nossos pensamentos, fazemos o nosso mundo. - Buda',
            'O que somos é consequência do que pensamos. - Buda',
            'Toma conselhos com o vinho, mas toma decisões com a água. - Benjamin Franklin',
            'Um irmão pode não ser um amigo, mas um amigo será sempre um irmão. - Benjamin Franklin',
            'A preguiça anda tão devagar que a pobreza facilmente a alcança. - Benjamin Franklin',
            'As três coisas mais difíceis do mundo são: guardar um segredo, perdoar uma ofensa e aproveitar o tempo. - Benjamin Franklin',
            'Pessoas que são boas em arranjar desculpas raramente são boas em qualquer outra coisa. - Benjamin Franklin',
            'Cultivar estados mentais positivos como a generosidade e a compaixão decididamente conduz a melhor saúde mental e a felicidade. - Dalai Lama',
            'Se você quer transformar o mundo, experimente primeiro promover o seu aperfeiçoamento pessoal e realizar inovações no seu próprio interior. - Dalai Lama',
            'O egoísmo causa a ignorância, a cólera e o descontrole, que são a origem dos problemas do mundo. - Dalai Lama',
            'Ele esbarrou na felicidade, tinha desistido de procurar a perfeição. - Brione Capri',
            'O importante não é vencer todos os dias, mas lutar sempre. - Waldemar Valle Martins',
            'Nossa maior fraqueza está em desistir. O caminho mais certo de vencer é tentar mais uma vez. - Thomas Edison',
            'O entusiasmo é a maior força da alma. Conserva-o e nunca te faltará poder para conseguires o que desejas. - Napoleon Hill',
            'As pessoas costumam dizer que a motivação não dura sempre. Bem, nem o efeito do banho, por isso recomenda-se diariamente. - Zig Ziglar',
            'Quem ousou conquistar e saiu pra lutar, chega mais longe! - Charlie Brown Jr',
            'Perder para a razão, sempre é ganhar. - Aldo Novak',
            'O insucesso é apenas uma oportunidade para recomeçar com mais inteligência. - Henry Ford',
            'Mesmo desacreditado e ignorado por todos, não posso desistir, pois para mim, vencer é nunca desistir. - Albert Einstein',
            'Ama-se mais o que se conquista com esforço. - Benjamin Disraeli',
            'O segredo de qualquer conquista é a coisa mais simples do mundo: saber o que fazer com ela. - Desconhecido',
            'Você nunca alcança o sucesso verdadeiro a menos que você goste do que está fazendo. - Dale Carnegie',
            'Nunca perca a fé , nunca pare de lutar, busque seus objetivos , nunca deixe de sonhar. - Bruna Morando',
            'Nunca pare de lutar pelo seu objetivo - Keellynhaa',
            'Duas coisas são infinitas: o universo e a estupidez humana. Mas, em relação ao universo, ainda não tenho certeza absoluta. - Albert Einstein',
            'A imaginação é mais importante que o conhecimento. - Albert Einstein',
            'Não tentes ser bem-sucedido, tenta antes ser um homem de valor. - Albert Einstein',
            'O mundo não está ameaçado pelas pessoas más, e sim por aquelas que permitem a maldade. - Albert Einstein',
            'Penso noventa e nove vezes e nada descubro; deixo de pensar, mergulho em profundo silêncio e eis que a verdade se me revela. - Albert Einstein',
            'A força não provém da capacidade física. Provém de uma vontade indomável. - Mahatma Gandhi',
            'Olho por olho, e o mundo acabará cego. - Mahatma Gandhi',
            'O medo tem alguma utilidade, mas a covardia não. - Mahatma Gandhi',
            'Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado. - Roberto Shinyashiki',
            'Acredite em si próprio e chegará um dia em que os outros não terão outra escolha senão acreditar com você. - Cynthia Kersey',
            'Quer você acredite que consiga fazer uma coisa ou não, você está certo. - Henry Ford',
            'O insucesso é apenas uma oportunidade para recomeçar com mais inteligência. - Henry Ford',
            'Pensar é o trabalho mais difícil que existe. Talvez por isso tão poucos se dediquem a ele. - Henry Ford',
            'Não encontro defeitos. Encontro soluções. Qualquer um sabe queixar-se. - Henry Ford',
            'Quer você acredite que consiga fazer uma coisa ou não, você está certo. - Henry Ford',
            'Estar decidido, acima de qualquer coisa, é o segredo do êxito. - Henry Ford',
            'Não é o empregador quem paga os salários, mas o cliente. - Henry Ford',
            'Corte sua própria lenha. Assim, ela aquecerá você duas vezes. - Henry Ford',
            'Questionar quem deve ser o chefe, é como discutir quem deve ser o saxofonista num quarteto: evidentemente, quem o sabe tocar. - Henry Ford',
            'Sei que metade da publicidade que faço é inútil. Mas não sei qual é a metade inútil. - Henry Ford',
            'Não encontre defeitos, encontre soluções. Qualquer um sabe queixar-se. - Henry Ford',
            'O melhor uso do capital não é fazer dinheiro, mas sim fazer dinheiro para melhorar a vida. - Henry Ford',
            'Nada é difícil se for dividido em pequenas partes. - Henry Ford',
            'A riqueza de uma nação se mede pela riqueza do povo e não pela riqueza dos príncipes. - Adam Smith',
            'O verdadeiro valor das coisas é o esforço e o problema de as adquirir. - Adam Smith',
            'A ciência é o grande antídoto do veneno do entusiasmo e da superstição. - Adam Smith',
            'A ambição universal do homem é colher o que nunca plantou. - Adam Smith',
            'O grande segredo da educação consiste em orientar a vaidade para os objetivos certos. - Adam Smith',
            'Felicidade é aquilo que ganhamos pelo agir. - Adam Smith',
            'Se tu o desejas, podes voar, só tens de confiar muito em ti. - Steve Jobs',
            'Às vezes, a vida vai te acertar um tijolo na cabeça. Não perca a fé. - Steve Jobs',
            'Design é função, não forma. - Steve Jobs',
            'Para mim, não há nada mais importante no futuro que o desenho. É a alma de tudo o que é criado pelo homem. - Steve Jobs',
            'Você pode encarar um erro como uma besteira a ser esquecida ou como um resultado que aponta uma nova direção. - Steve Jobs',
            'Cada sonho que você deixa pra trás, é um pedaço do seu futuro que deixa de existir. - Steve Jobs',
            'As pessoas não sabem o que querem, até mostrarmos a elas. - Steve Jobs',
            'Foco é dizer não. - Steve Jobs',
            'Concentre-se naquilo que você é bom, delegue todo o resto. - Steve Job',
            'As pessoas ligam a televisão quando querem desligar o cérebro. - Steve Jobs',
            'Seja um padrão de qualidade. As pessoas não estão acostumadas a um ambiente onde o melhor é o esperado. - Steve Jobs',
            'Se você viver cada dia de sua vida como se fosse o último, um dia você estará certo. - Steve Jobs',
            'Não deixe que o ruído da opinião alheia impeça que você escute a sua voz interior. - Steve Jobs',
            'A maior invenção do mundo não é a minha tecnologia! É a morte! pois através dela, o velho sempre dará lugar para o novo! - Steve Jobs',
            'Parece que você está apenas à procura de alguém para ficar zangado em vez de si próprio. - Steve Jobs',
            'Nascemos, vivemos por um momento breve e morremos. Tem sido assim há muito tempo. A tecnologia não está mudando muito este cenário. - Steve Jobs',
            'Parece que você está apenas à procura de alguém para ficar zangado em vez de si próprio. - Steve Jobs',
            'A não ser que o identificador de chamada diga que é Deus ligando, você não deve atender ao telefone durante a missa. - Steve Jobs',
            'Você tem que encontrar o que você ama! - Steve Jobs',
            'O sucesso é um professor perverso. Ele seduz as pessoas inteligentes e as faz pensar que jamais vão cair. - Bill Gates',
            'Seus clientes mais insatisfeitos são sua melhor fonte de aprendizado. - Bill Gates',
            'O tamanho trabalha contra a excelência. - Bill Gates',
            'Há uma certa responsabilidade que se acumulou sobre mim quando obtive esta posição inesperada. - Bill Gates',
            'As únicas grandes companhias que conseguirão ter êxito são aquelas que consideram os seus produtos obsoletos antes que os outros o façam. - Bill Gates',
            'O modo como você reúne, administra e usa a informação determina se vencerá ou perderá. - Bill Gates',
            'É claro que darei computadores aos meus filhos, mas antes terão livros. - Bill Gates',
            'A informática está interligada ao mundo sobre as reações intergalaxias! - Bill Gates',
            'É bom comemorar o sucesso, mas é mais importante prestar atenção às lições do fracasso. - Bill Gates',
            'A melhor forma de prever o futuro é criá-lo. - Alan Kay',
            'Se você não falha em pelo menos 90% das vezes, seus objetivos não foram ambiciosos o suficente. - Alan Kay',
            'Você pode sonhar, criar, desenhar e construir o lugar mais maravilhoso do mundo. Mas é necessário ter pessoas para transformar seu sonho em realidade. - Walt Disney',
            'Se você pode sonhá-lo,você pode fazê-lo. - Walt Disney',
            'Para começar, pare de falar e comece a fazer. - Walt Disney',
            'Não deixe que os seus medos tomem o lugar dos seus sonhos. - Walt Disney',
            'Todos os nossos sonhos podem-se realizar, se tivermos a coragem de persegui-los. - Walt Disney',
            'Os sonhos existem para tornarem-se realidade. - Walt Disney',
            'Se você consegue sonhar algo, consegue realizá-lo! - Walt Disney',
            'É divertido fazer o impossível! - Walt Disney',
            'Eu gosto do impossível porque lá a concorrência é menor. - Walt Disney',
            'Fé, duas letras que podem mudar sua vida, acredite. - (Peter Pan) Walt Disney',
            'Eu posso ensinar qualquer coisa a qualquer um, menos a sorrir. - Walt Disney',
            'Quantas coisas perdemos por medo de perder. - Paulo Coelho',
            'Uma vez feita a escolha é preciso seguir adiante e confiar no seu próprio coração... - Paulo Coelho',
            'Quando se ama não é preciso entender o que se passa lá fora, pois tudo passa a acontecer dentro de nós. - Paulo Coelho',
            'A possibilidade de realizarmos um sonho é o que torna a vida interessante. - Paulo Coelho',
            'Seja foda, o mundo já tá cheio de gente medíocre! - Desconhecido',
            'A felicidade às vezes é uma bênção, mas geralmente é uma conquista. - Paulo Coelho',
            'O maior de todos os pecados: o arrependimento. - Paulo Coelho',
            'Não prever, é já lamentar. - Leonardo da Vinci',
            'Quando eu pensar que aprendi a viver, terei aprendido a morrer. - Leonardo da Vinci',
            'Não há coisa que mais nos engane do que o nosso juízo. - Leonardo da Vinci',
            'O olhar de quem odeia é mais penetrante do que o olhar de quem ama. - Leonardo da Vinci',
            'Quero dar a meus filhos bastante dinheiro para que possam fazer o que quiserem, mas não dinheiro o bastante para que não façam nada. - Warren Buffett',
            'Alguém está sentado na sombra hoje porque alguém plantou uma árvore há muito tempo. - Warren Buffett',
            'São necessários 20 anos para construir uma reputação e apenas cinco minutos para destruí-la. - Warren Buffett',
            'Por algum motivo, as pessoas se baseiam nos preços e não nos valores. Preço é o que você paga. Valor é o que você leva. - Warren Buffett',
            'Regra número 1: nunca perca dinheiro. Regra número 2: não esqueça a regra número 1. - Warren Buffett',
            'Se a história passada fosse tudo o que importa no jogo, as pessoas mais ricas seriam os bibliotecários. - Warren Buffett',
            'Se você acertou, pare de tentar. - Warren Buffett',
            'Não importa quão sereno o dia de hoje pode ser, o amanhã é sempre incerto. Não deixe essa realidade assustar você. - Warren Buffett',
            'O risco vem de não saber o que você está fazendo. - Warren Buffett',
            'A diversificação é uma proteção contra a ignorância. Faz pouquíssimo sentido para quem sabe o que está fazendo. - Warren Buffett',
            'A diferença entre pessoas bem sucedidas e pessoas realmente bem sucedidas é que as pessoas realmente bem sucedidas dizem não a quase tudo. - Warren Buffett',
            'Você só descobre quem está nadando pelado quando a maré é baixa. - Warren Buffett',
            'Previsões geralmente nos falam mais sobre quem faz a previsão do que da previsão em si. - Warren Buffett',
            'Quando alguém vê o vizinho ficando mais rico, começa a evolução natural da bolha. Bastam três coisas para a sua formação: os inovadores, os imitadores e os idiotas. - Warren Buffett',
            'Wall Street é o único lugar onde as pessoas chegam em um Rolls-Royce para obter conselhos daqueles que pegam o metrô. - Warren Buffett',
            'Se você não encontrar um jeito de ganhar dinheiro enquanto dorme, você vai trabalhar até morrer. - Warren Buffett',
            'Você não precisa ser esperto, só precisa ser paciente. - Warren Buffett',
            'Amor e tosse, impossível ocultá-los. - George Herbert',
            'Você tem que acordar cada manhã com determinação se você pretende ir para a cama com satisfação. - George Lorimer',
            'Tente mover o mundo. O primeiro passo será mover a si mesmo. - Platão',
            'Não corrigir nossas falhas é o mesmo que cometer novos erros. - Confúcio',
            'É fazendo que se aprende a fazer aquilo que se deve aprender a fazer. - Aristóteles',
            'A imaginação é mais importante que o conhecimento. - Albert Einstein',
            'Os obstáculos são aquelas coisas terríveis que você vê quando desvia os olhos do seu objetivo. - Henry Ford',
            'Se há algum segredo de sucesso, consiste ele na habilidade de apreender o ponto de vista da outra pessoa e ver as coisas tão bem pelo ângulo dela como pelo seu. - Henry Ford',
            'O sucesso é um professor perverso. Ele seduz as pessoas inteligentes e as faz pensar que jamais vão cair. - Bill Gates',
            'Todos precisamos de pessoas que nos dêem feedback. É assim que melhoramos. - Bill Gates',
            'O DNA humano é como um programa de computador, mas muito mais avançado do que qualquer software jamais inventado. - Bill Gates',
            'Foco é dizer não. - Steve Jobs',
            'Seu trabalho vai preencher uma parte grande da sua vida, e a única maneira de ficar realmente satisfeito é fazer o que você acredita ser um ótimo trabalho. E a única maneira de fazer um excelente trabalho é amar o que você faz. - Steve Jobs',
            'Você pode encarar um erro como uma besteira a ser esquecida ou como um resultado que aponta uma nova direção. - Steve Jobs',
            'Estamos aqui para fazer alguma diferença no universo. Se não, porque estar aqui? - Steve Jobs',
            'Não faz sentido olhar para trás e pensar: devia ter feito isso ou aquilo, devia ter estado lá. Isso não importa. Vamos inventar o amanhã e parar de nos preocupar com o passado. - Steve Jobs',
            'Nascemos, vivemos por um momento breve e morremos. Tem sido assim há muito tempo. A tecnologia não está mudando muito este cenário. - Steve Jobs',
            'Se tu o desejas, podes voar, só tens de confiar muito em ti. - Steve Jobs',
            'Computadores são como bicicletas para nossas mentes. - Steve Jobs',
            'A tecnologia move o mundo. - Steve Jobs',
            'A maior invenção do mundo não é a minha tecnologia! É a morte! pois através dela, o velho sempre dará lugar para o novo! - Steve Jobs',
            'Vamos inventar o amanhã e parar de nos preocupar com o passado. - Steve Jobs',
            'Às vezes a vida te acerta na cabeça com um tijolo. Não perca a fé. Estou convencido de que a única coisa que me manteve no caminho foi amar o que eu fazia. Você precisa encontrar aquilo que ama. - Steve Jobs',
            'Decidir o que não fazer é tão importante quanto decidir o que fazer. - Steve Jobs',
            'Seu tempo é limitado, então não o desperdice vivendo a vida de outra pessoa. Não deixe que a opinião dos outros cale a sua voz interior. - Steve Jobs',
            'Criatividade é a arte de conectar ideias. - Steve Jobs',
            'Inovação é a capacidade de ver a mudança como uma oportunidade não uma ameaça. - Steve Jobs',
            'Não encontre defeitos, encontre soluções. Qualquer um sabe queixar-se. - Henry Ford',
            'O passado serve para evidenciar as nossas falhas e dar-nos indicações para o progresso do futuro. - Henry Ford',
            'Um idealista é uma pessoa que ajuda os outros a prosperar. - Henry Ford',
            'Qualquer um que parar de aprender é velho, seja aos 20 ou aos 80 anos. Qualquer pessoa que mantém a aprendizagem continua jovem. A coisa mais importante da vida é manter sua mente jovem. - Henry Ford',
            'Quando tudo tiver parecendo ir contra você, lembre-se que o avião decola contra o vento, e não a favor dele. - Henry Ford',
            'Só existem 2 dias do ano em que você não pode fazer nada: um se chama ontem, e o outro amanhã. - Dalai Lama',
            'Para ser um campeão, você tem que acreditar em si mesmo quando ninguém mais acredita. - Muhammad Ali',
            'No fim, tudo dá certo, e se não deu certo é porque ainda não chegou ao fim. - Fernando Sabino',
            'Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados. - Mahatma Gandhi',
            'A coisa mais difícil é a decisão de agir, o resto é apenas tenacidade. - Amelia Earhart',
            'A vida é o que acontece com você enquanto você está ocupado fazendo planos. - John Lennon',
            'Ganhar não é tudo, mas querer ganhar é. - Vince Lombardi',
            'Cada criança é um artista. O problema é permanecer um artista depois que crescemos. - Pablo Picasso',
            'Você nunca pode atravessar o oceano até que você tenha coragem de perder de vista a costa. - Cristóvão Colombo',
            'Os dias mais importantes na sua vida são o dia em que você nasce, e o dia em que você descobre o porquê. - Mark Twain',
            'Como é maravilhoso que ninguém precise esperar um momento antes de começar a melhorar o mundo. - Anne Frank',
            'Fiquei impressionado com a urgência de fazer. Saber não é suficiente; devemos aplicar. Estar disposto não é o suficiente; devemos fazer. - Leonardo Da Vinci',
            'Vencer sem correr riscos é triunfar sem glórias. - Ayrton Senna',
            'A persistência é o caminho do êxito. - Charles Chaplin',
            'Tudo acontece por uma razão. - John Locke',
            'A dificuldade é a maneira da natureza de te tornar mais forte. - John Locke',
            'Algumas pessoas querem que algo aconteça, outras desejam que algo aconteça, outras fazem acontecer. - Michael Jordan',
            'Os verdadeiros heróis são feitos de trabalho pesado e integridade. - Hope Solo',
            'Não tenho compromisso com a vitória, mas tenho o compromisso de ser verdadeiro. Não tenho compromisso com o sucesso, mas tenho o compromisso de viver de acordo com a luz que tenho. - Abraham Lincoln',
            'Quando algo é importante o suficiente, você o faz mesmo quando as probabilidades não estejam a seu favor. - Elon Musk',
            'A vida só pode ser compreendida olhando para trás, mas só pode ser vivida olhando para frente. - O Curioso Caso de Benjamin Button',
        ])->random();
    }
}